name: Build and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * SUN'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ##########################
      # [ PHP 7.4-cli-buster ] #
      ##########################

      -
        name: Build & Push [ PHP 7.4-cli-buster ]
        id: docker_build_php74_cli_buster
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./php/7.4-cli-buster/Dockerfile
          tags: vitorarantes/php:7.4-cli-buster

      ##########################
      # [ PHP 8.0-cli-buster ] #
      ##########################

      -
        name: Build & Push [ PHP 8.0-cli-buster ]
        id: docker_build_php80_cli_buster
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./php/8.0-cli-buster/Dockerfile
          tags: vitorarantes/php:8.0-cli-buster

      ##########################
      # [ PHP 8.0-cli-alpine ] #
      ##########################

      -
        name: Build & Push [ PHP 8.0-cli-alpine ]
        id: docker_build_php80_cli_alpine
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./php/8.0-cli-alpine/Dockerfile
          tags: vitorarantes/php:8.0-cli-alpine
