name: Build and Push

on:
  release:
    types:
      - created
  schedule:
    - cron: '0 1 * * SUN'

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'php') || github.event_name == 'schedule' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ##########################
      # [ PHP 8.0-fpm-alpine ] #
      ##########################

      - name: Build & Push [ PHP 8.0-fpm-alpine ]
        if: ${{ contains(github.ref, 'php-8.0-fpm-alpine') || github.event_name == 'schedule' }}
        id: docker_build_php80_fpm_alpine
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./php/8.0-fpm-alpine/Dockerfile
          tags: vitorarantes/php:8.0-fpm-alpine

      ##########################
      # [ PHP 8.0-cli-alpine ] #
      ##########################

      - name: Build & Push [ PHP 8.0-cli-alpine ]
        if: ${{ contains(github.ref, '8.0-cli-alpine') || github.event_name == 'schedule' }}
        id: docker_build_php80_cli_alpine
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./php/8.0-cli-alpine/Dockerfile
          tags: vitorarantes/php:8.0-cli-alpine
